---
grails:
    security:
        salt: 5c0744940b5c369b
    profile: web
    codegen:
        defaultPackage: orsan
    gsp:
        tldScanPattern: 'classpath*:/META-INF/*.tld,/WEB-INF/tld/*.tld'

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

endpoints:
    jmx:
        unique-names: true

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        neo4j:
            url: "http://localhost:7474"
            urlWithAuth: "http://neo4j:0rs%40np%40ssw0RD@localhost:7474"
            username: "neo4j"
            password: "0rs@np@ssw0RD"
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        grails:
            plugin:
                cloudinary:
                    cloudName: "yawosoft"
                    apiKey: "393785181811382"
                    apiSecret: "-or_mvrQf4AjDvovIy6XMnPIUBo"
                    enhanceImageTag: true
                    staticImageSupport: false
        facebook:
                    clientId: 281707958585235
                    clientSecret: 321c9a03128b568bda9f6f4abc79fe94
                    scope: "email, public_profile, user_about_me, user_location, user_hometown, user_birthday"
        twitter:
            consumerKey: 0
            consumerSecret: 0
        google:
            consumerKey: "629252203032-m8q026fm2ld1a7moov05rk48oi81hj6d.apps.googleusercontent.com"
            consumerSecret: "OfP7XfChMna_VZ7uoZesyn0-"
            scope: "profile,email"
            key: "AIzaSyBCfGYBAXwol-DgOzwzqOpo6rhhtuFUPRQ"

    test:
        neo4j:
            url: "http://localhost:7474"
            urlWithAuth: "http://neo4j:0rs%40np%40ssw0RD@localhost:7474"
            username: "neo4j"
            password: "0rs@np@ssw0RD"
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        grails:
            plugin:
                cloudinary:
                    cloudName: "yawosoft"
                    apiKey: "393785181811382"
                    apiSecret: "-or_mvrQf4AjDvovIy6XMnPIUBo"
                    enhanceImageTag: true
                    staticImageSupport: false
        facebook:
            clientId: 281707958585235
            clientSecret: 321c9a03128b568bda9f6f4abc79fe94
            scope: "email, public_profile, user_about_me, user_location, user_hometown, user_birthday, offline_access"
        twitter:
            consumerKey: 0
            consumerSecret: 0
        google:
            consumerKey: "629252203032-m8q026fm2ld1a7moov05rk48oi81hj6d.apps.googleusercontent.com"
            consumerSecret: "OfP7XfChMna_VZ7uoZesyn0-"
            scope: "profile,email"

    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        grails:
            plugin:
                cloudinary:
                    cloudName: "yawosoft"
                    apiKey: "393785181811382"
                    apiSecret: "-or_mvrQf4AjDvovIy6XMnPIUBo"
                    enhanceImageTag: true
                    staticImageSupport: true
